blog/urls.py
from django.urls import path
from .views import ArticleList, ArticleDetail, CategoryList


app_name = "blog"

urlpatterns = [
    path('', ArticleList.as_view(), name="home"),
    path('page/<int:page>', ArticleList.as_view(), name="home"),
    path('home/<slug:slug>', ArticleDetail.as_view(), name="detail"),
    path('category/<slug:slug>', CategoryList.as_view(), name="category"),
    path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name="category")
]

weblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account.views import Login


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', Login.as_view(), name='login'),
    path('', include('django.contrib.auth.urls')),
    path('', include('blog.urls')),
    path('comment/', include('comment.urls')),
    path('account/', include('account.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
#from django.db.models.deletion import SET_NULL
from django.utils import timezone
from extensions.utils import jalali_converter
from django.utils.html import format_html
from account.models import User
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment
# my managers


class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')


class CategoryManager(models.Manager):
    def published(self):
        return self.filter(status=True)
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=20, verbose_name="نام دسته بندی")
    parent = models.ForeignKey('self', null=True, blank=True, default=None,
                               on_delete=models.SET_NULL,
                               related_name='children', verbose_name='زیر دسته')
    position = models.IntegerField(verbose_name="پوزیشن")
    status = models.BooleanField(default=True, verbose_name="منتشر شود؟")
    slug = models.SlugField(max_length=100, unique=True,
                            verbose_name="اسلاگ دسته بندی")
    
    class Meta:
        ordering = ['parent__id', 'position']
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"

    def __str__(self):
        return self.name
    objects = CategoryManager()


class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیشنویس'),
        ('p', 'منتشر شده'),
        ('i', 'درحال بررسی'),
        ('b', 'برگشت داده شده'),
    )
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='articles', verbose_name='نویسنده')
    title = models.CharField(max_length=100, verbose_name="عنوان مقاله")
    slug = models.SlugField(max_length=100, unique=True,
                            verbose_name="آدرس مقاله")
    description = models.TextField(verbose_name="محتوا")
    thumbnail = models.ImageField(upload_to="images", verbose_name="تصویر")
    publish = models.DateTimeField(default=timezone.now,
                                   verbose_name="زمان انتشار")
    Category = models.ManyToManyField(Category, related_name="articles")
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES,
                              verbose_name="وضعیت")
    is_special = models.BooleanField(default= False, verbose_name= "مقاله ویژه")
    comments = GenericRelation(Comment)
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"
        ordering = ['-publish', 'status']
    
    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description = "زمان انتشار"
    
    def thumbnail_tag(self):
        return format_html("<img width=100 height=75 style='border-radius: 5px;' src='{}'>".format(self.thumbnail.url))
    
    def get_absolute_url(self):
        return reverse("account:home")
    
    def category_to_str(self):
        CatList = [i.name for i in self.Category.published()]
        return ", ".join(CatList)
    category_to_str.short_description = "دسته بندی ها"
        
    objects = ArticleManager()

blog/views.py
from django.core import paginator
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from .models import Article, Category
from django.views.generic import ListView, DetailView

class ArticleList(ListView):
    queryset = Article.objects.published()
    paginate_by = 4

#def detail(request, slug):
#    context = {
#        "article": get_object_or_404(Article, slug=slug, status="p"),
#        
#    }
#    return render(request, "blog/detail.html", context)

class ArticleDetail(DetailView):
    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Article.objects.published(),slug= slug)


#def category(request, slug, page=1):
#    category = get_object_or_404(Category, slug=slug, status=True)
#    article_list = category.articles.published()
#    paginator = Paginator(article_list, 4)
#    articles = paginator.get_page(page)
#    context = {
#        "category": category,
#        "articles": articles
#    }
#    return render(request, 'blog/category.html', context)
#

class CategoryList(ListView):
    paginate_by = 5
    def get_queryset(self):
        slug = self.kwargs.get('slug')
        global category
        category = get_object_or_404(
            Category.objects.published(),slug= slug)
        return category.articles.published()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context

blog/templates/blog/article_detail.html
{% extends 'blog/Base.html' %}
{% block title %}|{{object.title}} {% endblock %}
{% block Article %}

<header class="masthead" style="background-image: url('{{article.thumbnail.url}} ')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
          <div class="col-lg-8 col-md-10 max-auto">
              <div class="site-heading">
                  <center>
                    <h1>{{article.title}} </h1>
                    <time>{{i.jpublish}}</time>
                  </center>
              </div>
          </div>
      </div>
    </div>
</header>


     <article>
        <center>
         <h1>{{article.title}}</h1>
         <small> {{article.jpublish}} </small>
        </center>
        <p class="detai text-justify"> {{article.description|linebreaks}} </p>
     </article

{% endblock %}

blog/templates/blog/article_list.html
{% extends 'blog/Base.html' %}
{% load static %}
{% load Base_tags %}
{% block main %}

<body id="page-top">
 
    <header class="masthead d-flex align-items-center">
        <div class="container px-4 px-lg-5 text-center">
            <h1 class="mb-1">به امتحانات آنلاین خوش آمدید</h1>
            <h3 class="mb-5"><em>A Free Bootstrap Theme by Start Bootstrap</em></h3>
            
        </div>
    </header>
 

     <article>
        {% for i in object_list %}
        <center>
        <img src=" {{i.thumbnail.url}} " alt=" {{i.title}} " width="400" height="320">
        </center>
        <h1><a href = "{% url 'blog:detail' i.slug %}">{{i.title}}</a></h1>
        
        <small class="post-meta"> {{i.jpublish}}
            <p>نوشته شده توسط {{i.author}} </p>
        </small>
        <p class="article text-justify"> {{i.description|truncatewords:30}} </p>
        <div>
            {% for Category in i.Category.all %}
            <a href="{% url 'blog:category' Category.slug %}">#{{ Category.name }} </a>
            {% endfor %}
        </div>
        <hr>
        
        {% endfor %}
        </article>
    
        <div class="pager-botton">
            
           {% if is_paginated %}
                {% if page_obj.has_next %}
                   <a class="btn btn-primary btn-xl" href="{% url 'blog:home' page_obj.next_page_number %} ">صفحه بعد &rarr;</a>
                {% endif %}
                {% if page_obj.has_previous %}
                    <a class="btn btn-primary btn-xl" href="{% url 'blog:home' page_obj.previous_page_number %} ">صفحع قبل &larr;</a>
                {% endif %}
           {% endif %}    
        </div>
        <!-- Footer-->
    <footer class="footer text-center">
        <div class="container px-4 px-lg-5">
            <ul class="list-inline mb-5">
                <li class="list-inline-item">
                    <a class="social-link rounded-circle text-white mr-3" href="#!"><i class="icon-social-facebook"></i></a>
                </li>
                <li class="list-inline-item">
                    <a class="social-link rounded-circle text-white mr-3" href="#!"><i class="icon-social-twitter"></i></a>
                </li>
                <li class="list-inline-item">
                    <a class="social-link rounded-circle text-white" href="#!"><i class="icon-social-github"></i></a>
                </li>
            </ul>
            <p class="text-muted small mb-0">Copyright &copy; Your Website 2021</p>
            
        </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top"><i class="fas fa-angle-up"></i></a>
    <!-- Bootstrap core JS-->
    <script src="{% static 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
{% endblock %}